### ISSUE TITLE
Naming Scheme for contact-sheet Script

### ISSUE THREAD

**Issue by AngelaDMerkel** [cezary-zemis/ExifNotes_process#1]
What is the naming scheme to run the contact-sheet script? I have a series of images which have already been tagged and whose names are sequentially numbered. 

Running script gives me this error:

```
Traceback (most recent call last):
  File "/Users/$USER/Downloads/ExifNotes_process-master/contact-sheet", line 59, in <module>
    if not sys.argv[1]:
           ~~~~~~~~^^^
IndexError: list index out of range
$USER@$USER 230113.109.F.120.645.200+0.C41 % python3 /Users/$USER/Downloads/ExifNotes_process-master/contact-sheet
Traceback (most recent call last):
  File "/Users/$USER/Downloads/ExifNotes_process-master/contact-sheet", line 59, in <module>
    if not sys.argv[1]:
           ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by cezary-zemis** [comment]
The issue is not about file naming, the script should take every *.jpg, *.jpeg, *.tif, *.tiff (no case sensitive) files except `*_contact[-_]sheet.*`. You have to run the script with one or two parameters:
- one parameter is one of the following pre-defined frame formats: ff (135 full frame), 645, 66, 67, 69, 45, 57, 810; this is used to determine number of columns and rows
- two parameters: custom number of column and rows

**Comment by AngelaDMerkel** [comment]
How do I add the parameters? I modified the script so that I can import from the ExifNotes modules, but I still get the same error 

```
Traceback (most recent call last):
  File "/Users/$USER/Desktop/Images/contact-sheet", line 60, in <module>
    if not sys.argv[1]:
           ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by cezary-zemis** [comment]
e.g.:
`pasiasty@Kokoro-Ubuntu:~/Desktop/test 03$ contact-sheet 67`

**Comment by AngelaDMerkel** [comment]
Ok, thanks. Once I pass the argument I get a huge number of additional errors. 

```
Traceback (most recent call last):
  File "/Users/$USER/Desktop/Images/contact-sheet", line 127, in <module>
    fs = scale_font_to_image(tb, font_name, '\n'.join(descs[count]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/$USER/Desktop/Images/contact-sheet", line 17, in scale_font_to_image
    draw.font = ImageFont.truetype(fn, fs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
$USER@Jacquelyns-MacBook-Pro Images % python3 /Users/$USER/Desktop/Images/contact-sheet ff
Traceback (most recent call last):
  File "/Users/$USER/Desktop/Images/contact-sheet", line 127, in <module>
    fs = scale_font_to_image(tb, font_name, '\n'.join(descs[count]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/$USER/Desktop/Images/contact-sheet", line 17, in scale_font_to_image
    draw.font = ImageFont.truetype(fn, fs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
```

Please forgive me if this is frustrating for you

**Comment by cezary-zemis** [comment]
It looks like missing font issue. Use FONT_NAME environment variable to override default setting. On Linux/Unix it can be done the following way:
`$ FONT_NAME='Arial.ttf' contact-sheet 66`
I guess you can use the same way on MacOS.

**Comment by AngelaDMerkel** [comment]
I have managed to get this to work. Thank you so much for your help. I'll close the issue now.
